#!/usr/bin/env python3
"""Regenerate src/i18n/error_catalog.cpp from the storage/protocol layers.

Those layers throw plain English messages (require(..., "text") and
std::runtime_error("text")). The desktop translates them where it shows them,
in the "bm::Errors" context; this catalogue exists only so lupdate extracts
them. Run it after changing such a message, or with --check (as CI does) to
fail when the catalogue is out of date.
"""
import glob
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "i18n" / "error_catalog.cpp"
# The UI layers translate their own messages with tr().
SKIP = {"session.cpp", "desktop_window.cpp", "main.cpp"}
CALL = re.compile(r'(?:require\([^;]*?,\s*|runtime_error\()\s*("(?:[^"\\]|\\.)*"(?:\s*"(?:[^"\\]|\\.)*")*)\s*\)', re.S)


def messages():
    found = []
    for path in sorted(glob.glob(str(ROOT / "src" / "*.cpp"))):
        if pathlib.Path(path).name in SKIP:
            continue
        for match in CALL.finditer(pathlib.Path(path).read_text()):
            text = "".join(re.findall(r'"((?:[^"\\]|\\.)*)"', match.group(1)))
            if re.search(r"[A-Za-z]{3}", text) and text not in found:
                found.append(text)
    return found


def render(found):
    lines = [
        "// Generated by scripts/update-error-catalog.py -- do not edit by hand.",
        "// English messages thrown by the storage, protocol and delivery layers,",
        '// translated for display in the "bm::Errors" context. Read by lupdate only;',
        "// this file is not compiled into any target.",
        "#include <QtGlobal>",
        "static const char *const kErrorCatalog[] = {",
    ]
    lines += [f'    QT_TRANSLATE_NOOP("bm::Errors", "{text}"),' for text in found]
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    text = render(messages())
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT} is out of date; run scripts/update-error-catalog.py", file=sys.stderr)
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
